"""make channel_id nullable

Revision ID: b2d57182bfc6
Revises: 59e68c1c3e8c
Create Date: 2026-07-28 20:26:28.844481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d57182bfc6'
down_revision: Union[str, Sequence[str], None] = '59e68c1c3e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'channel_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index(op.f('ix_channels_handle'), table_name='channels')
    op.create_index(op.f('ix_channels_handle'), 'channels', ['handle'], unique=True)
    op.create_unique_constraint(None, 'channels', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_index(op.f('ix_channels_handle'), table_name='channels')
    op.create_index(op.f('ix_channels_handle'), 'channels', ['handle'], unique=False)
    op.alter_column('channels', 'channel_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
